/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dataAccess.MidiaDAO;
import domainModel.Midia;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lewandowsky
 */
public class frmListagemArquivos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListagemMidias
     */
    public frmListagemArquivos() {
        initComponents();
        preencheTabela();
    }

    private void preencheTabela(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome do Arquivo");
        modelo.addColumn("Caminho");
        modelo.addColumn("Data de Criação");
        modelo.addColumn("Tamanho");
        DateFormat df = new SimpleDateFormat ("dd/MM/yyyy HH:mm:ss.SSS");  
        int id = 0;
        for(File a : this.listaArquivos){
            Vector v = new Vector();
            ++id;
            v.add(0,id);
            v.add(1,a.getName());
            v.add(2,a.getPath());
            Date tmpData = new Date(a.lastModified());
            df.format(tmpData);
            
            v.add(3,tmpData);
            v.add(4,(a.length() / 1024));
            //v.add(3,a.getTipo());
            modelo.addRow(v);
        
        }
        
        this.tblListaArquivos.setModel(modelo);
        this.tblListaArquivos.repaint();
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaArquivos = new javax.swing.JTable();
        lblFiltro = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();
        cbjFiltro = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setTitle("Listagem de Arquivos");
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));

        tblListaArquivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListaArquivos);

        lblFiltro.setText("Filtro");

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        cbjFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Nome" }));
        cbjFiltro.setToolTipText("Selecione o tipo de Filtro");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFiltro)
                        .addGap(26, 26, 26)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(cbjFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFiltro)
                        .addGap(122, 122, 122))))
            .addGroup(layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltro)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltro)
                    .addComponent(cbjFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        int opcao = cbjFiltro.getSelectedIndex();
        MidiaDAO dao = new MidiaDAO();
        switch(opcao){
        
            case 0:
                this.listaArquivos.clear();
                for(Midia m : dao.listarMidias()){
                    for(File f : m.getListaDeArquivos()){
                        this.listaArquivos.add(f);
                    }
                }
                preencheTabela();
                break;
            case 1:
                this.listaArquivos.clear();
               for(Midia m : dao.listarMidias()){
                    for(File f : m.getListaDeArquivos()){
                        if(f.getName().matches("(?i).*"+ txtFiltro.getText() +".*")){
                            this.listaArquivos.add(f);
                        }
                    }
                }
                
                preencheTabela();
                break;
         
        }
    }//GEN-LAST:event_btnFiltroActionPerformed
    private List<File> listaArquivos = new LinkedList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private javax.swing.JComboBox cbjFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JTable tblListaArquivos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
